### ISSUE TITLE
iOS Contact Image not cropped

### ISSUE THREAD

**Issue by scriptPilot** [capacitor-community/contacts#108]
**Describe the bug**
When adding a contact photo via iOS Contacts and crop the face from a large image, the large image is retrieved not only the cropped face as expected.

**To Reproduce**
1. Create a new contact in iOS Contacts
2. Choose a lager image
3. Crop a face
4. Save
5. Retrieve contact with this API

**Expected behavior**
Cropped image / face retrieved as base64 string.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro, iOS 16 - other iOS devices same behavior

**Additional context**
- No problem with photos synchronized from Google Contacts

**Comment by tafelnl** [comment]
The `CNContactStore` in Swift provides the following two image types:

[`CNContactImageDataKey`](https://developer.apple.com/documentation/contacts/cncontactimagedatakey) and [`CNContactThumbnailImageDataKey`](https://developer.apple.com/documentation/contacts/cncontactthumbnailimagedatakey).

Currently it's returning the value belonging to the `CNContactImageDataKey`. I'm not sure if the `CNContactThumbnailImageDataKey` would return a 'cropped' variant. It would return a thumbnail though. So I'm not sure if that is desirable. What do you think?

If you have access to Xcode, you could easily test the difference between to two by the way. Just navigate to the source code and swap:
- the [occurences of `CNContactImageDataKey`](https://github.com/search?q=repo%3Acapacitor-community%2Fcontacts+CNContactImageDataKey&type=code) with `CNContactThumbnailImageDataKey`
- [`contact.imageData`](https://github.com/search?q=repo%3Acapacitor-community%2Fcontacts+CNContactImageDataKey&type=code) with `contact.thumbnailImageData`

**Comment by tafelnl** [comment]
In that case I am afraid it's not possibly to do what you want. Because Apple does not offer any other thing in their `CNContact` API that I know of

**Comment by scriptPilot** [comment]
Ok - thanks for looking into it.
