### ISSUE TITLE
Add Phone Number Labels

### ISSUE THREAD

**Issue by stevecarlton** [capacitor-community/contacts#12]
**Is your feature request related to a problem? Please describe.**
I have used the Cordova Contacts plugin for many years and original underestimated how important the labels are for phone numbers. Without them, very little context is offered.

**Describe the solution you'd like**
I am very novice in swift but managed to add labels to the phoneNumbers array returned from getContacts in iOS with
```
for number in contact.phoneNumbers {
     let numberToAppend = number.value.stringValue
     let labelToAppend = number.label?.replacingOccurrences(of: "[!$_<>]", with: "", options: .regularExpression, range: nil)
     phoneNumbers[labelToAppend] = numberToAppend                      
 }
```
That might be horrible practice in Swift but it's working for me.

**Describe alternatives you've considered**
Without adding the label to each phone number it will be very difficult to know which number needs to be selected in an app using this plugin.

**Comment by tnoetzel** [comment]
@stevecarlton - Curious if you got this running for Android as well, and if you'd be willing to share your forked plugin code. I'm definitely interested in this functionality, and I'm guessing others are, too.

**Comment by vhinic** [comment]
I'm just about to create pull request for adding labels for phone numbers as well as emails - in case anyone is interested.

**Comment by vhinic** [comment]
I will push PR for sample code in https://github.com/byrdsandbytes/capContactsDemo/tree/capacitor-community as well.

**Comment by Idrimi** [comment]
tested and works. 👍 thx @vhinic. closing this.

**Comment by stevecarlton** [comment]
@vhinic thanks for making this happen!
