### ISSUE TITLE
Contact Photos in Result

### ISSUE THREAD

**Issue by scriptPilot** [capacitor-community/contacts#14]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
An array of linked contact photos in the result.

**Describe alternatives you've considered**
The main contact photo as string.

**Additional context**
n/a

**Comment by vhinic** [comment]
I have this ready - just doing some testing. Will submit PR in the morning - in case anyone is interested

**Comment by scriptPilot** [comment]
@vhinic - Thank you :-) In fact I switched over to native Swift development as it was easier for me compared to all the workarounds. But probably I can use it in another project.

**Comment by vhinic** [comment]
Ah, I'm to late :(. @scriptPilot hopefully we get you back to hybrid world soon. Perhaps some of the code, is useful example for your native solution as well.

**Comment by Idrimi** [comment]
Finally was able to test it. Works. Thx @vhinic for the contribution.

**Comment by vhinic** [comment]
Glad to help
