### ISSUE TITLE
Missing birthday, organizationName and organizationRole on iOS

### ISSUE THREAD

**Issue by vhinic** [capacitor-community/contacts#18]
**Describe the bug**
When running on iOS `birthday`, `organizationName` and `organizationName` are not populated in returned contacts structure.

**To Reproduce**
1. On iOS call `Contacts.getContacts()`
2. Observe returned contacts array and notice that  `birthday`, `organizationName` and `organizationName` are missing.

**Expected behavior**
Expecting to have  `birthday`, `organizationName` and `organizationName` populated for contacts that have birthday and organization/copany in native contacts app - same as on Android.

**Comment by Idrimi** [comment]
thx @vhinic. merged. closing issue.
