### ISSUE TITLE
Have to sync gradle first before import can be resolved

### ISSUE THREAD

**Issue by tafelnl** [capacitor-community/contacts#2]
I followed all the steps in the docs.
But when importing the Contacts class like described in the docs:
`import ch.byrds.capacitor.contacts.Contacts;`

I received the following error: `Cannot resolve symbol ch`

As a solution I added an extra random character to the gradle file and clicked the sync button that then appears
![image](https://user-images.githubusercontent.com/35837839/87018676-e0ad4980-c1d1-11ea-9cbe-516a62790358.png)

Then I removed the random character and synced again.

This made the error disappear.

I am not sure if this is an error with Capacitor itself (i tried running `cap update`, `cap sync` and `cap copy` but none helped) or something else

**Comment by Idrimi** [comment]
I have no idea, what's reason for this. Can't reproduce either. Does it still happen in v.0.0.3?

**Comment by tafelnl** [comment]
For anyone reading this: this is completely "normal" behavior. It can and should indeed be solved by running Gradle sync. I've added it to the docs as well: https://capacitor-community.github.io/contacts/#/guide/troubleshooting
