### ISSUE TITLE
Ionic 5 + Vue 3 Support

### ISSUE THREAD

**Issue by recoiladam** [capacitor-community/contacts#20]
**Describe the bug**
I am trying to use this plugin with Ionic 5 + Vue 3 since the Cordova Contact plugin seems to be deprecated however, I am unable to get it to work and I am unable to find any documentation related to Ionic 5 + Vue 3 + Capactor plugins that works. If you have any insight, I would appreciate it.

**To Reproduce**
The code below is what I have tried. Essentially, there's a button that calls "chooseContacts" but nothing happens and the iOS console log simply shows "error" and nothing else.

```
<script>
import { defineComponent } from 'vue';
import { Plugins } from '@capacitor/core'

export default defineComponent({
  mounted() {
    this.contacts = Plugins
  },
  methods: {
    chooseContacts() {
      this.contacts.getContacts().then(results => {
        console.log(results)
      })
    }
  }
});
</script>
```

**Expected behavior**
I am expecting the console log to show a list of contacts as the result.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: NA
 - Version: NA

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: iOS 14.?
 - Browser: NA
 - Version: NA

**Comment by adarshmadrecha** [comment]
Try :

```js
import { defineComponent } from 'vue';
import { Plugins } from '@capacitor/core'
const  { Contacts } = Plugins;

export default defineComponent({
  mounted() {
    this.contacts = Contacts 
  },
  methods: {
    chooseContacts() {
      this.contacts.getContacts().then(results => {
        console.log(results)
      })
    }
  }
});

```

I guess you have not imported the Contact from plugin.

**Comment by pagelyadam** [comment]
This issue can be closed.

**Comment by Idrimi** [comment]
perfect.
