### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by dwieeb** [capacitor-community/contacts#21]
Hi @Idrimi, I don't think we've been introduced. Would you be able to join the [Capacitor Contributors slack](https://getcapacitor.herokuapp.com/)? I'd like to add you to our channel if that's alright.

I also have a few questions (we can chat in Slack):
- What's the purpose this repo? https://github.com/capacitor-community/capacitor-contacts-plugin
- Any plans for updating this plugin for Capacitor 3 (now in beta)?

**Comment by vhinic** [comment]
@Idrimi I'm really looking for support for capacitor 3, as well. I'm also waiting for several PRs I did more than a month ago. Please help me to support this plugin. I do not want to start another one in parallel...

**Comment by Idrimi** [comment]
Hello there. Took a while. As every dev, I'm busy building delivery apps at the moment. 😏🥑
@vhinic had a look at your PRs. Seems all good to me and is merged. Could you double check on iOS thumbnail fetching? on Android i had no issues. 

@dwieeb joined slack. Let's have a chat there. 

- That's the old version of the plugin. I can't remember forking it in here. So in can be deleted from cap-community.
- Yeah, sure. Any place/links,docs for plugin creation in v3?

@vhinic thanks for contributing btw. proper code.

**Comment by vhinic** [comment]
@Idrimi I can sympathize... thanks for pushing this through. I have few more to go and will validate again on iOS and report here.

**Comment by Idrimi** [comment]
@vhinic perfect. I try to not let you wait that long next time. Have a good night.
