### ISSUE TITLE
Which plugin is being maintained @capacitor-community/contacts or @byrds/capacitor-contacts?

### ISSUE THREAD

**Issue by jimbarrett33** [capacitor-community/contacts#23]
**Describe the bug**
This plugin **@capacitor-community/contacts** crashes on Android so I tried the referenced demo app in the README and it does NOT crash. However, the demo app uses a different plug-in **@byrds/capacitor-contacts**. 

Is the source code for these plugins supposed to be identical? I'm confused why both exist and why the one under "capacitor-community" is the one that is crashing. It's also confusing that this plugin points to a demo app at the uses a different plugin.

**Comment by Idrimi** [comment]
This one here is maintained. The other one is/will be deprectated.
Check the different branches in the demo repo. If you using the "capacitor-community" branch you're using the this plugin 
here.
https://github.com/byrdsandbytes/capContactsDemo/tree/capacitor-community
Master branch still uses byrds plugin.

**Comment by jimbarrett33** [comment]
@Idrimi Thanks for getting back so quickly! I'm going to close this issue.
