### ISSUE TITLE
Failing to compile Plugin.swift

### ISSUE THREAD

**Issue by gianlazz** [capacitor-community/contacts#27]
**Describe the bug**
> A clear and concise description of what the bug is.

After installing the plugin with npm and syncing with capacitor I'm unable to compile my project in xcode.

The following errors are thrown in the Plugin.swift file:
- `Invalid conversion from throwing function of type '(Bool) throws -> Void' to non-throwing function type '(Bool) -> Void'` Line 34
- `Consecutive statements on a line must be separated by ';'` Line 87
- `Expected expression` Line 87
- `Expected '}' in class` Line 98

**To Reproduce**
1. npm i --save @capacitor-community/contacts
2. npx cap sync
3. build in xcode

**Expected behavior**
> A clear and concise description of what you expected to happen.

I expect it to build.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="1280" alt="Screen Shot 2021-02-02 at 8 01 29 PM" src="https://user-images.githubusercontent.com/1166579/106696432-8f134480-6591-11eb-9ffd-734c751d5fce.png">

<img width="1288" alt="Screen Shot 2021-02-02 at 8 01 39 PM" src="https://user-images.githubusercontent.com/1166579/106696463-9d616080-6591-11eb-8b34-fde8ab872997.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina v10.15.5
- Xcode: 12.4 (12D4e)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS v14.3
 - Ionic: v5
 - Capacitor: v2.4.4
 - Plugin Version: v0.1.0

**Comment by Idrimi** [comment]
Hi,

haven't tried to reproduce it yet, but I can see that you're using "npm install @ionic-native/contacts". Which ist the Cordova plugin not the capacitor plugin. That could cause the issue.

**Comment by thesurya9** [comment]
facing the same issue, let me know if you found the solution.

**Comment by gianlazz** [comment]
> Hi,
> 
> 
> 
> haven't tried to reproduce it yet, but I can see that you're using "npm install @ionic-native/contacts". Which ist the Cordova plugin not the capacitor plugin. That could cause the issue. 

Oh whoops that was a typo on my part with the issue.

**Comment by ViteRoberto** [comment]
I had the same issue. I just realized that the Plugin.swift file afte the last commited from @Idrimi was missing a } to close the IF statement in line 73. **So I just added the missing } in line 81** and it fixes the issue. I dont know how to correct that for everybody, im new answering and collaborating in GitHub. Hope i can help

**Comment by Idrimi** [comment]
Hi, 

should be fixed with PR#28, version 0.1.1. .
Make sure to install the latest version:
`npm i @capacitor-community/contacts@latest`

@gianlazz thx for reporting.
@ViteRoberto thx, you made the search for the missing "}" shorter.

Sry, for the issue.
