### ISSUE TITLE
Business Name

### ISSUE THREAD

**Issue by recoiladam** [capacitor-community/contacts#29]
**Is your feature request related to a problem? Please describe.**

On iOS devices, if the contact has a phone number and a business name but no first or last name, the contact returned is simply the phone number. When displaying this information on a contact list selector, it makes for a bad user experience.

Example JSON key value pair object:

```
      {
         "phoneNumbers":[
            "(000) 000-0000"
         ],
         "contactId":"6AA19AB6-16CF-4325-9E3B-5EDF948AC577:ABPerson",
         "displayName":" ",
         "emails":[
            
         ]
      }
```

**Describe the solution you'd like**

It would be nice of the business name was returned in the object. The documentation says "organizationName" should exist however, using version 0.1.1 of the plugin, I do not see this key value pair, even empty.

**Describe alternatives you've considered**

For now, we're going to filter out phone numbers that do not have a first and / or last name.

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: you will now be able to query the organization name of a contact.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
