### ISSUE TITLE
Android app crash on Deny permission

### ISSUE THREAD

**Issue by uxinnuendo** [capacitor-community/contacts#31]
**Describe the bug**
App crash on "Deny" permission selection (Android only)

**To Reproduce**
1. Request permission prompt
2. Tap 'Deny'

**Expected behavior**
Catch the failure internally and return { granted: false } from Contacts.getPermissions()

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: Android 10
 - Browser: stock browser

**Additional context**
AndroidManifest.xml:
`<uses-permission android:name="android.permission.READ_CONTACTS" />
      <uses-permission
        android:name="android.permission.READ_PROFILE"
        android:maxSdkVersion="29" />
<uses-permission android:name="android.permission.WRITE_CONTACTS" />`

**Comment by vkyeswa** [comment]
I created a pull request to handle this

**Comment by kwab** [comment]
See this: https://github.com/capacitor-community/contacts/issues/22 for a solution.

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships with improved checking and requesting of permissions: it now follows the new standards defined by the Capacitor team.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
