### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/contacts#32]
### Is your feature request related to a problem? Please describe.
The Capacitor 3 RC is out! 🎉 This library should support the new version

### Describe the solution you'd like
Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0

### Additional context
The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

**Comment by Idrimi** [comment]
@thomasvidas thx. Was waiting for this. I will upgrade it as soon as i have a spare moment.

**Comment by Dave-Nandwa** [comment]
Hi Thomas,

Noticed v0.1.1 is not working on iOS with Capacitor v2.4.4 - Is that because of Capacitorv3 or a bug?

My package.json:

```
"dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@capacitor-community/contacts": "^0.1.1",
    "@capacitor-community/fcm": "^1.1.0",
    "@capacitor/core": "^2.4.4",
    "@capacitor/ios": "^2.4.4",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/pwa-elements": "^3.0.2",
    "apexcharts": "^3.23.1",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "firebase": "^7.10.0",
    "moment": "^2.27.0",
    "ng-apexcharts": "^1.5.6",
    "ngx-image-cropper": "^3.3.3",
    "ngx-spinner": "^10.0.1",
    "rxjs": "~6.5.5",
    "sweetalert2": "^10.13.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@capacitor/cli": "^2.4.4",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },
```

**Comment by KirstenStake** [comment]
@Idrimi hello, do you have any timelines on when you think you'd be able to upgrade the plugin to support Capacitor v3.0?

**Comment by Idrimi** [comment]
Hi Kristen,

just tried it this weekend. You can test the develop branch. Should work with cap 3.

**Comment by KirstenStake** [comment]
@Idrimi hmm getting a few errors when trying to build my app using the develop branch of the plugin. Few errors with "browser doesn't contain a valid alias configuration".

I might just have to wait till develop gets merged into master when you are happy with it.

**Comment by Idrimi** [comment]
@KirstenStake Android or iOS? iOS is tested. Android will follow.

**Comment by KirstenStake** [comment]
@Idrimi error was being received when trying to build for ios. Steps I did were:

1. installed the develop branch directly from the repo via npm
2. npm installed @capacitor/core@next as was requiring it as a peer dependency
3. built for ios

Error received:
Cannot find module '@capacitor-community/contacts' or its corresponding type declarations.

How I imported the plugin in my .ts file was as follows
`import { Contacts } from '@capacitor-community/contacts';`

as the previous way of 
`import { Plugins } from '@capacitor/core';
const { Contacts } = Plugins;`
is no longer possible for cap v3 and also threw an error

**Comment by Idrimi** [comment]
Thx for testing. i'll have a look at it. 
The way you do the  import seems right. 
Do not know how to migrate Apps  to cap 3 properly yet. Had to kill ios plattform completely, then add it again. 
This branch here is working: https://github.com/byrdsandbytes/capContactsDemo/tree/develop using a local version of the plugin

**Comment by kainosnoema** [comment]
@Idrimi @KirstenStake the reason using the branch doesn't work is because the package doesn't get built (so `dist` is missing) when installing from a branch. Can add `prepare` to `package.json` to make testing a branch easier: https://blog.jim-nielsen.com/2018/installing-and-building-an-npm-package-from-github.

**Comment by najmulansari** [comment]
HI @Idrimi,
I am also stuck with this. Any update on Contacts to support on Capacitor 3?

**Comment by kainosnoema** [comment]
I have a private fork that's working well with Capacitor 3. Might find some time to open a PR or two if @Idrimi doesn't already have plans to finish adding support.

**Comment by thomasvidas** [comment]
@Idrimi can re-open if he would like, but I've published 1.0.5 of`@capacitor-community/contacts`. The code is from the latest `develop` branch to npm so it is easier for people to install and use in their projects. To install, use `npm i @capacitor-community/contacts@next`

**Comment by Idrimi** [comment]
@kainosnoema yeah, open a PR maybe i can take some inspiration for android support.

**Comment by Yuripetusko** [comment]
@Idrimi only Android actually but I have iOS here also will check in a bit

**Comment by Yuripetusko** [comment]
Actually I do have one problem after an update, when doing `npx pod sync` this morning after an update I get `update ios - failed! No podspec found for `CapacitorCommunityContacts``

**Comment by crabbydavis** [comment]
After manually adding the podspec iOS works

**Comment by Idrimi** [comment]
thx @Yuripetusko for testing. Missing podspec file is fixed.

**Comment by Idrimi** [comment]
I'm closing the issue.
https://github.com/capacitor-community/contacts/releases/tag/1.0.9

**Comment by gsglobalpro** [comment]
> Thx for testing. i'll have a look at it.
> The way you do the import seems right.
> Do not know how to migrate Apps to cap 3 properly yet. Had to kill ios plattform completely, then add it again.
> This branch here is working: https://github.com/byrdsandbytes/capContactsDemo/tree/develop using a local version of the plugin

doesn't display number type label etc
