### ISSUE TITLE
Some contact fields are missing even though they are present on the contact card

### ISSUE THREAD

**Issue by EfosaSO** [capacitor-community/contacts#33]
**Describe the bug**
When loading in contacts, some of their already present fields are missing. Fields such as birthday date are returned undefined, even though the contact has that saved on the contact card.

This is happening for many contacts.

**To Reproduce**
1. Just load contacts

**Expected behavior**
To see all fields present on the contact card.

**Screenshots**
![IMG_54CC39CC3832-1](https://user-images.githubusercontent.com/22990506/112124253-0fc9e680-8bba-11eb-84aa-5227a47dda04.jpeg)
![Group](https://user-images.githubusercontent.com/22990506/112124355-2a9c5b00-8bba-11eb-91d2-8afb0521846a.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.5

**Comment by TylerAHolden** [comment]
Per this block: https://github.com/capacitor-community/contacts/blob/2532167b04a185f2f768400bbecabb23ccd2882d/ios/Plugin/ContactsPlugin.swift#L77-L86

It looks like only birthday is returned if the user has a thumbnail photo?? I'm not sure why this would make sense to block this data if the user doesn't have a thumbnail. I saw another PR merged into a dev branch that might've solved this. Would like to see that merged into a release version.

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: the birthday and organization fields will be returned, independently of a contact's thumbnail photo.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
