### ISSUE TITLE
Missing middleName in displayName on IOS

### ISSUE THREAD

**Issue by molobala** [capacitor-community/contacts#35]
**Describe the bug**

The plugin does not add `middleName` in  contact `displayName`

**To Reproduce**
1. Create new capacitor project
2. Add this plugin
3. Fetch contact list and display `diaplayName` 
4. You will see the `displayName` does not include `middleName` for contacts where it exists  

**Expected behavior**
The displayName should include`givenName`,`middleName`, and `famillyName`  

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS14.2
 - Browser safari

**Additional context**
Change line `68` in Plugin.swift to `"displayName": "\(contact.givenName) \(contact.middleName) \(contact.familyName)",` should fix the issue.

**Comment by Idrimi** [comment]
@molobala will check if android & ios have a middle name field. Thx for the additional context. That helps.

**Comment by bbehling** [comment]
We have a big need for givenName and familyName fields. The only work around for this library is to split at the first occurrence of a space in the display name. Any updates on when this will be available?

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships with a `name` object ([docs](https://capacitor-community.github.io/contacts/#/api?id=namepayload)) with different name properties. On both Android and iOS it will also return a `name.display` that essentially concatenates the different name fields, with the help of native helpers of Android and iOS.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
