### ISSUE TITLE
Contacts for PWA using javascript || jquery

### ISSUE THREAD

**Issue by antonyf** [capacitor-community/contacts#38]
I apologise in advance for writing this here, i could find a link to contact the developer direct.

How would i get this contacts plugin to work on a PWA using JavaScript or jQuery ? and is this possible? I'm busy learning about Capacitor. I have searched for days now, but not finding any conclusive information. Hence I'm writing here. A example would would also be appreciated. Greets Tony

**Comment by Idrimi** [comment]
Hi Tony,

check here for a working Demo-PWA using this plugin. Feel free top copy paste. https://github.com/byrdsandbytes/capContactsDemo/tree/develop
