### ISSUE TITLE
(feature) Write Contact

### ISSUE THREAD

**Issue by elvisgraho** [capacitor-community/contacts#39]
There is no mention of writing a contact in Readme and typescript didn't give me any clues.

Readme, however, mentions writing in Android permissions.

Thank you.

**Comment by Idrimi** [comment]
Hi @elvisgraho for the moment we're not planing to implement a writing feature into the plugin. The plugin should be lightweight and maintainable. It does one job. Fetching contacts fast. Writing contacts is a rare use-case, as it can be covered by native functions and therefore is not on our list. But feel free to fork.

**Comment by tafelnl** [comment]
Actually this feature got implemented in October 2021 :tada: 

---

On a side note:

A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: you will be able to create a contact ([docs](https://capacitor-community.github.io/contacts/#/api?id=createcontact)).

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
