### ISSUE TITLE
Contacts.getPermissions on android - unexpected first call result

### ISSUE THREAD

**Issue by s-r-x** [capacitor-community/contacts#57]
**Describe the bug**

Hello.
On android Contacts.getPermissions returns object with a shape {"contacts": "granted" } instead of { granted: true } on first call(e.g. when user did not give the permissions yet), but { granted: true } on the subsequent calls. 
I believe that the root of evil is [here](https://github.com/capacitor-community/contacts/blob/master/android/src/main/java/ch/byrds/capacitor/contacts/Contacts.java#L62), and it looks like #40 is going to fix it.

**To Reproduce**

1. Call Contacts.getPermissions() on android without granted or denied permissions
2. Check the output

```typescript
import { Contacts } from "@capacitor-community/contacts";
const perm = await Contacts.getPermissions();
```
**Expected behavior**

Should always return { granted: true|false }

**Screenshots**

![Screenshot_20211116_131326](https://user-images.githubusercontent.com/41614937/141946565-9261e729-5eb9-4660-ba83-45ee931121fc.png)
![Screenshot_20211116_131343](https://user-images.githubusercontent.com/41614937/141946576-818dbe50-147e-4cea-8bfe-200d4e3ee640.png)

**Smartphone (please complete the following information):**
 - OS: Android 11

**Comment by Idrimi** [comment]
@s-r-x that's unfortunate. Probably came with the last PR. I will have look at it.

**Comment by RRGT19** [comment]
Any update on this? I'm facing the same issue with the latest version of the plugin and capacitor.

**Comment by s-r-x** [comment]
@RRGT19 you can write your own abstraction over getPermissions. Something like this should work:
```ts
import { Contacts } from "@capacitor-community/contacts";
async function getPermissions() {
  const perm = await Contacts.getPermissions();
  return {
    granted: perm.contacts === "granted" || perm.granted
  }
}
```

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships with improved checking and requesting of permissions: it now follows the new standards defined by the Capacitor team.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
