### ISSUE TITLE
Get Physical Address

### ISSUE THREAD

**Issue by klenzoid** [capacitor-community/contacts#61]
There is a way to input the physical address of contact. However,  according to the Interface there is no way to retrieve it.

**Describe the solution you'd like**
Add Address with an Address Interface

**Describe alternatives you've considered**
There is no alternative

**Comment by halversonmd** [comment]
I have an [open pull request](https://github.com/capacitor-community/contacts/pull/63) that does this for iOS.

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: you will now be able to query the postal addresses of a contact.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
