### ISSUE TITLE
Ability to delete contact

### ISSUE THREAD

**Issue by moblizeit** [capacitor-community/contacts#65]
**Is your feature request related to a problem? Please describe.**
It seems there is no way to delete the contact.

**Describe the solution you'd like**
I would like to have the ability to delete the contact from address book so that my app can help user keep the address book clean as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: you will now be able to delete a contact ([docs](https://capacitor-community.github.io/contacts/#/api?id=deletecontact)).

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
