### ISSUE TITLE
Ionic capacitor 3 project getting cannot resolve ch in mainactivity

### ISSUE THREAD

**Issue by fitprotracker** [capacitor-community/contacts#70]
Walking through the example and getting the error in the mainactivity.java file.

![image](https://user-images.githubusercontent.com/52284584/164261721-34df3d8f-168b-45a6-accb-93d8a0df48ba.png)

any thoughts?

**Comment by scottwilson312** [comment]
Same issue here, on a completely vanilla project

**Comment by scottwilson312** [comment]
I upgraded my gradle inside android studio from 4.x to 7.x and now all is well

**Comment by tafelnl** [comment]
This is a common error, that is caused by forgetting to run `npx cap sync` and/or forgetting to run Gradle sync. I am happy you were able to resolve the issue in the end. I have added it to the documentation as well: https://capacitor-community.github.io/contacts/#/guide/troubleshooting
