### ISSUE TITLE
Extra whitespace is being added in contact name on saveContact() 

### ISSUE THREAD

**Issue by kulkarniyudhi** [capacitor-community/contacts#71]
**Extra whitespace is being added in contact name on saveContact()**
I tested this with android , extra whitespace is being added in contact name at end.
I think problem is : I am passing only  givenName and in plugin I can see there is middle and family name is being concatenated, 
so if no value is given for middle and family name it takes 2 whitespaces at end.

**To Reproduce**
1. Create blank ionic project
2. install capacitor-community/contacts plugin
3. save contact using Contact.saveContact() method only pass  givenName parameter

**Expected behavior**
Should not add extra spaces in name

**Screenshots**
![WhatsApp Image 2022-04-20 at 7 14 26 PM](https://user-images.githubusercontent.com/46275864/164405103-42a049f2-734e-4710-a674-20357dababd1.jpeg)

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships your request: the plugin does not extra whitespaces when saving name attributes.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!
