### ISSUE TITLE
Add support for Capacitor 4

### ISSUE THREAD

**Issue by RRGT19** [capacitor-community/contacts#77]
**Describe the bug**
When upgrading from Capacitor 3 to Capacitor 4, `npm install` fails with the message:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.0.1
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor-community/contacts@1.1.3
npm ERR! node_modules/@capacitor-community/contacts
npm ERR!   @capacitor-community/contacts@"^1.1.3" from the root project
```

**To Reproduce**
1. Upgrade to Capacitor 4
2. Install this plugin

**Expected behavior**
Install should not return any dependency error.

**Additional context**
Capacitor 4 has been released recently, see releases [here](https://github.com/ionic-team/capacitor/releases). The `peerDependencies` of this plugin need an update.

**Comment by oneclickwebstudio** [comment]
Hello! 
Is there any contributors here? Will you migrate plugin to Capacitor 4?

**Comment by dotNetkow** [comment]
Hi all, I just released support for Capacitor 4. No credit to me, I just pushed it through. All thanks to @rdlabo!

[Release notes](https://github.com/capacitor-community/contacts/releases/tag/v2.0.0)
