### ISSUE TITLE
🚀 Requesting permission to up the game

### ISSUE THREAD

**Issue by tafelnl** [capacitor-community/contacts#83]
@Idrimi @muuvmuuv @rdlabo @dotNetkow 

First of all thank you for everything you guys have done to make this plugin available for the capacitor community. 💪 

I have noticed maintenance of this plugin has somewhat stalled. Maybe the interest of the maintainer has shifted, or maybe they simply lack the time. Which is totally fair of course. Any work done for the open source community is just an extra, especially when it's done without any compensation at all. 🎖️ 

I was in need of a few (yet) unimplemented features. Recently I started adding those features to this plugin in a private fork. Eventually things escalated a bit, and I ended up refactoring a lot and finally I just wrote everything from scratch again. Haha.

I like to share my work with the capacitor community. It will close all but one open issues. I have written the plugin to support Capacitor v3, but I will also apply the necessary changes to support v4. That way both versions of Capacitor can be supported with the exact same plugin API.

I could just create a new repo and npm package. But I think it's more desirable to _not_ create a bunch of different repositories every time a new maintainers stands up and refactors a bunch of stuff. So therefore I am requesting the permission of you guys to mostly take over the maintainership of this plugin and release a v3 (unfortunately a v2 has just been shipped, so these will be following each other shortly, but oh well) and a v4 versions of the plugin.

Sidenote: I already have the necessary permissions and roles for this repository and npm, so you do not need to do anything in case you guys agree @dotNetkow 😄

**Comment by muuvmuuv** [comment]
Go ahead :D thanks for the work. I am very excited about your changes

**Comment by Idrimi** [comment]
@tafelnl perfectly fine for me. Will not have time to maintain it in the near future. So I'm happy if somebody takes care of the repo.

**Comment by tafelnl** [comment]
Alright, thanks for the responses guys. I will start moving my code to this repo probably starting this weekend. Need to do some last polishing first. 😄

**Comment by tafelnl** [comment]
I've just published two branches:

https://github.com/capacitor-community/contacts/tree/v3
https://github.com/capacitor-community/contacts/tree/v4

I'll probably merge v3 to main, and keep v4 rebased on v3. That way we can easily provide LTS for both versions.

@dotNetkow Could you give me permission to publish GitHub Pages for this repo? I've added extensive docs tailored for GitHub Pages :smile:

**Comment by dotNetkow** [comment]
OK @tafelnl I added you with a Maintain role. See if that works! I also turned on GH pages for main branch.
