### ISSUE TITLE
checkPermissions doesn't give back a response on iOS

### ISSUE THREAD

**Issue by RRGT19** [capacitor-community/contacts#92]
**Describe the bug**
I have updated the plugin from v2.0.0 to v4.0.0. While testing on both platforms, I have noticed that the `checkPermissions()` method doesn't do anything on `iOS`. Well, at least the native code is called, but I never received a response.

**To Reproduce**
1. Install the latest version of the plugin (v4)
2. Try to call the `checkPermissions()` method on iOS

**Expected behavior**
I should get a response from the method saying if it's granted, denied, etc...

**Screenshots**
Logs on iOS:

![Logs](https://i.ibb.co/9WzxqP3/Screenshot-2023-01-17-at-7-46-58-PM.png)

**The response is missing.**

Android for example, works correctly, see logs as a demonstration of the expected behavior:

![Logs](https://i.ibb.co/CH2G3pq/Screenshot-2023-01-17-at-7-55-40-PM.png)

**Smartphone:**
 - Device: iPhone 14 Emulator
 - OS: 16.2

**Additional context**
None so far.

**Comment by tafelnl** [comment]
I will investigate this shortly and get back to you with more information.

**Comment by tafelnl** [comment]
Resolved in #93 and released in `v3.0.1` and `v4.0.1`. Thanks for reporting!
